# Generated by Django 3.2.3 on 2021-06-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='time',
            new_name='timestamp',
        ),
    ]
