# Generated by Django 3.2.3 on 2021-06-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_developer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(default=('',), upload_to='image/'),
            preserve_default=False,
        ),
    ]
