# Generated by Django 3.2.3 on 2021-06-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_developer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='image',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='date',
        ),
        migrations.AddField(
            model_name='developer',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(default=('',), max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='mobile_number',
            field=models.CharField(default=('',), max_length=12),
            preserve_default=False,
        ),
    ]
