# Generated by Django 3.2.3 on 2021-06-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210622_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
