# Generated by Django 3.2.3 on 2021-06-22 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210622_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='developer',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
